# Generated by Django 5.0.3 on 2024-04-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToCo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='active_students',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='is_project_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='maincontent',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maincontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maincontent',
            name='title',
            field=models.CharField(max_length=155),
        ),
    ]
