# Generated by Django 5.0.3 on 2024-04-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToCo', '0002_maincontent_active_students_maincontent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontent',
            name='image',
        ),
    ]
