# Generated by Django 5.0.3 on 2024-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToCo', '0005_rename_is_project_active_maincontent_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
